# Generated by Django 5.1 on 2024-08-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_usersession_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='price',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='quantity',
        ),
        migrations.AddField(
            model_name='usersession',
            name='items',
            field=models.TextField(default='[]'),
        ),
    ]
