# Generated by Django 5.1 on 2024-08-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_usersession_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='current_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='current_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
