# Generated by Django 5.1 on 2024-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_usersession_current_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='current_description',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='current_quantity',
        ),
        migrations.AddField(
            model_name='usersession',
            name='temp_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
