# Generated by Django 5.1 on 2024-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_usersession_current_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='temp_data',
        ),
        migrations.AddField(
            model_name='usersession',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
