# Generated by Django 5.1 on 2024-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_orderitem_remove_usersession_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('pdf_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
